### PR TITLE
Inject XRay through the options

### PR DESCRIPTION
**Pull request by istanishev**

### CODE REVIEW

**Comment by tirianmal** [comment]
If you're going to remove the request require in the proxy.js file, you should also remove it from the package.json.

I believe that this will make the client usable in browser. But I've tried making these same changes in situ and haven't exactly gotten it working. Probably issues in cleaning out node_modules after making them.

If no one objects and we commit these changes, I'll try this out and see what happens.

**Comment by rnowosielski** [comment]
Looks good to me. Although if the intention is to make it work in a browser, I guess the request-promise-native will not work....

**Comment by istanishev** [comment]
You cannot remove `request` from packages.json as it is needed by the other package. See: https://github.com/request/request-promise-native

**Comment by rnowosielski** [comment]
Request promise could also be injectable. If somebody goes for Lambda, they can use `request-promise-native` and it the browser use is expected then `request-promise`. I assume most browsers don't support promises natively, right? Or maybe now they do?

**Comment by istanishev** [comment]
Hmm, if we are going to inject request, would it make sense to use more "supported" package for making http requests? What about axios? We've started using it quite a lot and it works everywhere.

**Comment by rnowosielski** [comment]
I don't have any strong feelings about which client should be used as long as it is not huge. So part of using the request-promise-native is that leverages the native promises and there is no need to pull deps such as bluebird and such deps that would in the end make the lambda package bigger (that was the problem we had before). I am not sure how many dependencies does axios pull, and the size of the resulting zip we put in the lambda is my only concern. 

We can give axios a shot I guess.

**Comment by istanishev** [comment]
https://www.npmjs.com/package/axios

It seems it has:
* 2 direct dependencies
* 2 indirect

**Comment by rnowosielski** [comment]
Seems pretty lightweight. Let's go for it.

**Comment by istanishev** [comment]
Closed in favor of #12

**Pull request closed without merging**
